trigger:
  branches:
    include:
    - 'master'
    - 'release-dev'

variables:
  prodReleaseBranchName: 'master' 
  devReleaseBranchName: 'release-dev'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      wwwrootDir: 'src/App/wwwroot'
      dotnetSdkVersion: '5.0.x'

    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'

    - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
      displayName: 'Write build info'
      workingDirectory: $(wwwrootDir)

    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - template: azure-templates/build.yml
      parameters:
        buildConfiguration: 'Debug'

    - template: azure-templates/build.yml
      parameters:
        buildConfiguration: 'Release'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      condition: succeeded()

- stage: 'Dev'
  displayName: 'Deploy to the dev environment'
  dependsOn: Build
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranchName'], variables['devReleaseBranchName'])
    )
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-templates/deploy.yml
            parameters:
              buildConfiguration: 'Debug'
              webAppName: '$(WebAppNameDev)'

- stage: 'Prod'
  displayName: 'Deploy to the prod environment'
  dependsOn: Build
  condition: |
    and
    (
      succeeded(),
      eq(variables['Build.SourceBranchName'], variables['prodReleaseBranchName'])
    )
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: prod
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-templates/deploy.yml
            parameters:
              buildConfiguration: 'Release'
              webAppName: '$(WebAppNameProd)'